# https://projecteuler.net/problem=44
# Pentagon numbers

'''
Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?
'''

def calc_pentagonal_number(n):
    pentagonal_number = n*(3*n-1)/2
    return(pentagonal_number)

def main():

    pent_nums = []
    for i in range(1, 10_000):
        pent_nums.append(calc_pentagonal_number(i))

    add_list = []
    sub_list = []
    for j in pent_nums:
        for k in pent_nums:    
            if (j+k) <= pent_nums[-1]:
                if (j+k) in pent_nums:
                    add_list.append((j,k))
            if (abs(j-k)) in pent_nums:
                sub_list.append((j,k))
            
    both = set(add_list).intersection(set(sub_list))
    print(both)

    return()



if __name__ == "__main__":
    main()